hidden_size_multiplier : 3    # Example hidden size for LSTM
num_layers_lstm : 1 # Number of LSTM layers
num_layers_dense : 1 # Number of Dense layers
dropout : 0.11919666682383416
norm_type : rmsnorm         
